site_name: Zero Um Company - Docs

repo_url: https://github.com/Zero-Um-company/DOCS
site_url: https://zero-um-company.github.io/DOCS/
edit_uri: edit/master/docs/

theme:
  name: material
  language: pt-BR

  logo: "assets/logo.png"

  features:
    - toc.integrate
    - toc.follow
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.instant
    - navigation.top

  hide:
    - toc

  extra:
    social:
      - type: github
        link: https://github.com/Zero-Um-company/DOCS

plugins:
  - search:
      lang: pt-BR

palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: dark blue
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Light
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: dark blue
    accent: amber
    toggle:
      icon: material/brightness-3
      name: Dark

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
